/* =====================================================================
   SMART DIGITAL LAUNDRY & STORE CARD — prototype logic
   Everything below runs on dummy, in-memory data. No backend/API calls.
   The physical laundry/store card is replaced by a digital wallet.
   Students generate a token (Laundry or Store); money is only deducted
   once hostel staff verify and confirm the token on the Staff
   Verification panel. This prevents students from deducting their own
   balance.
   ===================================================================== */

/* ---------------------- 1. DUMMY STUDENT DATA ---------------------- */

const student = {
  name: "Hasiba",
  regNo: "21CS1042",
  dept: "Computer Science & Engineering",
  hostel: "Ladies Hostel",
  block: "C",
  room: "214",
  cardId: "HL-2026-0842",
  cardStatus: "ACTIVE",
};

/* ---------------------- 2. WALLET ---------------------- */
// Wallet starts at ₹0. Hostel fee credit (simulated) sets it to ₹1000.
// Future implementation: automatic credit on real fee payment / ERP integration.

const wallet = {
  balance: 0,
  totalSpent: 0,
  count: 0,
};

/* ---------------------- 3. PRICING ---------------------- */
// Rates are NOT hardcoded into the logic — they live here so staff/admin
// can update them later without touching any calculation code.

const PRICING = {
  "Wash Only": { "5 KG": 50, "8 KG": 80 },
  "Wash & Dry": { "5 KG": 70, "8 KG": 110 },
  "Ironing": { perCloth: 10 },
};

/* ---------------------- 4. STAFF CREDENTIALS ---------------------- */
// Deliberately simple — laundry/store staff are not technical users.

const STAFF_CREDENTIALS = { username: "staff", password: "1234" };

/* ---------------------- 5. TRANSACTIONS ---------------------- */
// Every laundry / store token generated by the student lives here.
// status: "Waiting for Verification" | "Confirmed"

let transactions = [];
let laundryTokenSeq = 1025;
let storeTokenSeq = 2031;

/* Current in-progress laundry form selection */
let laundrySelection = { service: null, weight: null, clothType: "Shirt", quantity: 1 };

/* Token currently loaded in the staff verification result panel */
let staffActiveTokenId = null;

/* ---------------------- 6. HELPERS ---------------------- */

function formatDateTime(date = new Date()) {
  const datePart = date.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
  const timePart = date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
  return { date: datePart, time: timePart, label: `${datePart}, ${timePart}` };
}

function rupees(n) {
  return Number(n || 0).toLocaleString("en-IN");
}

function switchScreen(id) {
  document.querySelectorAll(".screen").forEach((s) => s.classList.remove("active"));
  document.getElementById(id).classList.add("active");
}

let toastTimer = null;
function showToast(message) {
  const toast = document.getElementById("toast");
  toast.textContent = message;
  toast.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toast.classList.remove("show"), 2600);
}

/* ---------------------- 7. STUDENT LOGIN ---------------------- */

const loginForm = document.getElementById("login-form");
loginForm.addEventListener("submit", (e) => {
  e.preventDefault();
  document.getElementById("screen-login").classList.remove("active");
  document.getElementById("app-shell").classList.add("active");
  document.getElementById("home-name").textContent = student.name.split(" ")[0];
  goTo("home");
  renderAll();
});

document.getElementById("btn-logout").addEventListener("click", () => {
  document.getElementById("app-shell").classList.remove("active");
  switchScreen("screen-login");
  goTo("home");
});

/* ---------------------- 8. STAFF LOGIN / LOGOUT ---------------------- */

document.getElementById("btn-goto-staff").addEventListener("click", () => {
  switchScreen("screen-staff-login");
});

document.getElementById("btn-back-to-student").addEventListener("click", () => {
  document.getElementById("staff-login-error").textContent = "";
  switchScreen("screen-login");
});

const staffLoginForm = document.getElementById("staff-login-form");
staffLoginForm.addEventListener("submit", (e) => {
  e.preventDefault();
  const username = document.getElementById("staff-input-username").value.trim();
  const password = document.getElementById("staff-input-password").value.trim();
  const errorEl = document.getElementById("staff-login-error");

  if (username === STAFF_CREDENTIALS.username && password === STAFF_CREDENTIALS.password) {
    errorEl.textContent = "";
    staffLoginForm.reset();
    resetStaffPanel();
    switchScreen("screen-staff");
  } else {
    errorEl.textContent = "Incorrect username or password.";
  }
});

document.getElementById("btn-staff-logout").addEventListener("click", () => {
  resetStaffPanel();
  switchScreen("screen-staff-login");
});

function resetStaffPanel() {
  staffActiveTokenId = null;
  document.getElementById("staff-token-input").value = "";
  document.getElementById("staff-search-error").textContent = "";
  document.getElementById("staff-result").hidden = true;
}

/* ---------------------- 9. STUDENT APP NAVIGATION ---------------------- */

const pageTitles = {
  home: "Home",
  card: "Digital Hostel Card",
  laundry: "Laundry Service",
  store: "Hostel Store",
  history: "Transaction History",
  profile: "Profile",
};

function goTo(pageName) {
  document.querySelectorAll(".page").forEach((p) => p.classList.remove("active"));
  const target = document.getElementById(`page-${pageName}`);
  if (target) target.classList.add("active");

  document.querySelectorAll(".nav-btn").forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.nav === pageName);
  });

  document.getElementById("topbar-title").textContent = pageTitles[pageName] || "Home";
  const mainEl = document.getElementById("app-main");
  if (typeof mainEl.scrollTo === "function") {
    mainEl.scrollTo({ top: 0, behavior: "smooth" });
  } else {
    mainEl.scrollTop = 0;
  }
}

document.querySelectorAll("[data-nav]").forEach((el) => {
  el.addEventListener("click", () => goTo(el.dataset.nav));
});

/* ---------------------- 10. HOME DASHBOARD ---------------------- */

function renderHome() {
  document.getElementById("home-block").textContent = `Block ${student.block}, Room ${student.room}`;
  document.getElementById("home-status").textContent = student.cardStatus;
  document.getElementById("balance-amount").textContent = rupees(wallet.balance);

  const payFeeBtn = document.getElementById("btn-pay-fee");
  payFeeBtn.style.display = wallet.balance === 0 ? "block" : "none";

  document.getElementById("card-name-1").textContent = student.name;
  document.getElementById("card-reg-1").textContent = student.regNo;
  document.getElementById("card-room-1").textContent = `${student.block}-${student.room}`;
  document.getElementById("card-id-1").textContent = `Card ID: ${student.cardId}`;

  const list = document.getElementById("home-recent");
  list.innerHTML = "";
  if (transactions.length === 0) {
    list.appendChild(buildEmptyRow("No transactions yet. Use Laundry or Store to get started."));
  } else {
    transactions.slice(0, 3).forEach((txn) => list.appendChild(buildTxnMiniItem(txn)));
  }
}

function buildEmptyRow(text) {
  const row = document.createElement("div");
  row.className = "mini-item";
  row.innerHTML = `<div class="mini-item-left"><div><p class="mini-item-title">${text}</p></div></div>`;
  return row;
}

function buildTxnMiniItem(txn) {
  const row = document.createElement("div");
  row.className = "mini-item";
  const isConfirmed = txn.status === "Confirmed";
  row.innerHTML = `
    <div class="mini-item-left">
      <div>
        <p class="mini-item-title">${txn.id} · ${txn.type}</p>
        <p class="mini-item-sub">${txn.service} · ₹${rupees(txn.amount)}</p>
      </div>
    </div>
    <span class="status-chip ${isConfirmed ? "confirmed" : "waiting"}">${txn.status}</span>
  `;
  return row;
}

document.getElementById("btn-pay-fee").addEventListener("click", () => {
  if (wallet.balance === 0) {
    wallet.balance = 1000;
    showToast("Hostel fee credited — ₹1000 added to your wallet");
    renderAll();
  } else {
    showToast("Hostel fee has already been credited this term");
  }
});

/* ---------------------- 11. DIGITAL CARD ---------------------- */

function renderCard() {
  document.getElementById("card-name-2").textContent = student.name;
  document.getElementById("card-reg-2").textContent = student.regNo;
  document.getElementById("card-dept-2").textContent = student.dept;
  document.getElementById("card-block-2").textContent = `${student.block} - ${student.hostel}`;
  document.getElementById("card-room-2").textContent = student.room;
  document.getElementById("card-balance-2").textContent = rupees(wallet.balance);
  document.getElementById("card-status-2").textContent = student.cardStatus;
  document.getElementById("profile-status").textContent = student.cardStatus;
}

/* ---------------------- 12. LAUNDRY MODULE ---------------------- */

const serviceOptions = document.getElementById("service-type-options");
const weightBlock = document.getElementById("laundry-weight-block");
const weightOptions = document.getElementById("weight-options");
const ironingBlock = document.getElementById("laundry-ironing-block");
const ironingClothSelect = document.getElementById("ironing-cloth-type");
const laundryAmountBar = document.getElementById("laundry-amount-bar");
const laundryAmountEl = document.getElementById("laundry-amount");
const laundryFormError = document.getElementById("laundry-form-error");
const btnGenerateLaundryToken = document.getElementById("btn-generate-laundry-token");

serviceOptions.addEventListener("click", (e) => {
  const btn = e.target.closest(".option-btn");
  if (!btn) return;

  laundrySelection.service = btn.dataset.service;
  laundrySelection.weight = null;

  [...serviceOptions.children].forEach((b) => b.classList.toggle("selected", b === btn));
  [...weightOptions.children].forEach((b) => b.classList.remove("selected"));

  const needsWeight = laundrySelection.service === "Wash Only" || laundrySelection.service === "Wash & Dry";
  const needsIroning = laundrySelection.service === "Ironing";

  weightBlock.hidden = !needsWeight;
  ironingBlock.hidden = !needsIroning;

  updateLaundryAmount();
});

weightOptions.addEventListener("click", (e) => {
  const btn = e.target.closest(".option-btn");
  if (!btn) return;
  laundrySelection.weight = btn.dataset.weight;
  [...weightOptions.children].forEach((b) => b.classList.toggle("selected", b === btn));
  updateLaundryAmount();
});

ironingClothSelect.addEventListener("change", () => {
  laundrySelection.clothType = ironingClothSelect.value;
});

document.getElementById("iron-qty-minus").addEventListener("click", () => {
  laundrySelection.quantity = Math.max(1, laundrySelection.quantity - 1);
  document.getElementById("iron-qty-value").textContent = laundrySelection.quantity;
  updateLaundryAmount();
});
document.getElementById("iron-qty-plus").addEventListener("click", () => {
  laundrySelection.quantity = Math.min(50, laundrySelection.quantity + 1);
  document.getElementById("iron-qty-value").textContent = laundrySelection.quantity;
  updateLaundryAmount();
});

function calculateLaundryAmount() {
  const { service, weight, quantity } = laundrySelection;
  if (!service) return 0;
  if (service === "Ironing") {
    return PRICING.Ironing.perCloth * quantity;
  }
  if (!weight) return 0;
  return (PRICING[service] && PRICING[service][weight]) || 0;
}

function isLaundrySelectionValid() {
  if (!laundrySelection.service) return false;
  if (laundrySelection.service === "Ironing") return laundrySelection.quantity > 0;
  return !!laundrySelection.weight;
}

function updateLaundryAmount() {
  const valid = isLaundrySelectionValid();
  const amount = calculateLaundryAmount();

  laundryAmountBar.hidden = !valid;
  laundryAmountEl.textContent = rupees(amount);
  btnGenerateLaundryToken.disabled = !valid;
  laundryFormError.textContent = "";
}

function resetLaundryForm() {
  laundrySelection = { service: null, weight: null, clothType: "Shirt", quantity: 1 };
  [...serviceOptions.children].forEach((b) => b.classList.remove("selected"));
  [...weightOptions.children].forEach((b) => b.classList.remove("selected"));
  weightBlock.hidden = true;
  ironingBlock.hidden = true;
  ironingClothSelect.value = "Shirt";
  document.getElementById("iron-qty-value").textContent = "1";
  laundryAmountBar.hidden = true;
  laundryAmountEl.textContent = "0";
  btnGenerateLaundryToken.disabled = true;
  laundryFormError.textContent = "";
}

btnGenerateLaundryToken.addEventListener("click", () => {
  if (!isLaundrySelectionValid()) {
    laundryFormError.textContent = "Please complete the service details before generating a token.";
    return;
  }

  const amount = calculateLaundryAmount();
  const { date, time, label } = formatDateTime();
  const isIroning = laundrySelection.service === "Ironing";

  const txn = {
    id: `LDY-${laundryTokenSeq++}`,
    type: "Laundry",
    service: laundrySelection.service,
    weight: isIroning ? null : laundrySelection.weight,
    clothType: isIroning ? laundrySelection.clothType : null,
    quantity: isIroning ? laundrySelection.quantity : null,
    amount,
    status: "Waiting for Verification",
    date,
    time,
    dateTimeLabel: label,
    remainingBalance: null,
  };

  transactions.unshift(txn);
  resetLaundryForm();
  showTokenSheet(txn);
  renderAll();
});

/* ---------------------- 13. STORE MODULE ---------------------- */

const storeDescriptionInput = document.getElementById("store-description");
const storeAmountInput = document.getElementById("store-amount");
const storeFormError = document.getElementById("store-form-error");

document.getElementById("btn-generate-store-token").addEventListener("click", () => {
  const amount = Number(storeAmountInput.value);

  if (!amount || amount <= 0) {
    storeFormError.textContent = "Please enter a valid purchase amount.";
    return;
  }

  storeFormError.textContent = "";
  const description = storeDescriptionInput.value.trim() || "Store Purchase";
  const { date, time, label } = formatDateTime();

  const txn = {
    id: `STR-${storeTokenSeq++}`,
    type: "Store",
    service: description,
    weight: null,
    clothType: null,
    quantity: null,
    amount,
    status: "Waiting for Verification",
    date,
    time,
    dateTimeLabel: label,
    remainingBalance: null,
  };

  transactions.unshift(txn);
  storeDescriptionInput.value = "";
  storeAmountInput.value = "";
  showTokenSheet(txn);
  renderAll();
});

/* ---------------------- 14. TOKEN GENERATED SHEET ---------------------- */

const overlay = document.getElementById("overlay");
const sheetList = document.getElementById("sheet-list");

function showTokenSheet(txn) {
  const rows = [];
  rows.push(`<div class="sheet-row"><span>Module</span><b>${txn.type}</b></div>`);
  rows.push(`<div class="sheet-row"><span>Service</span><b>${txn.service}</b></div>`);
  if (txn.weight) rows.push(`<div class="sheet-row"><span>Weight</span><b>${txn.weight}</b></div>`);
  if (txn.clothType) rows.push(`<div class="sheet-row"><span>Cloth Type</span><b>${txn.clothType} × ${txn.quantity}</b></div>`);
  rows.push(`<div class="sheet-row"><span>Amount</span><b>₹${rupees(txn.amount)}</b></div>`);

  sheetList.innerHTML = rows.join("");
  document.getElementById("sheet-token").textContent = txn.id;
  document.getElementById("sheet-status").textContent = "Waiting for Verification";
  overlay.classList.add("active");
}

document.getElementById("btn-close-sheet").addEventListener("click", () => {
  overlay.classList.remove("active");
  goTo("history");
});
overlay.addEventListener("click", (e) => {
  if (e.target === overlay) overlay.classList.remove("active");
});

/* ---------------------- 15. TRANSACTION HISTORY ---------------------- */

function renderHistory() {
  document.getElementById("stat-balance").textContent = rupees(wallet.balance);
  document.getElementById("stat-spent").textContent = rupees(wallet.totalSpent);
  document.getElementById("stat-count").textContent = wallet.count;

  const list = document.getElementById("history-list");
  list.innerHTML = "";

  if (transactions.length === 0) {
    const wrap = document.createElement("div");
    wrap.className = "timeline-item";
    wrap.innerHTML = `
      <span class="timeline-dot"></span>
      <div class="timeline-card">
        <div><p class="timeline-date">No transactions yet</p><p class="timeline-sub">Generate a laundry or store token to get started</p></div>
      </div>
    `;
    list.appendChild(wrap);
    return;
  }

  transactions.forEach((txn) => list.appendChild(buildHistoryItem(txn)));
}

function buildHistoryItem(txn) {
  const wrap = document.createElement("div");
  wrap.className = "timeline-item";

  const statusClass = txn.status === "Confirmed" ? "confirmed" : "waiting";
  const metaParts = [];
  if (txn.weight) metaParts.push(`<span>Weight <b>${txn.weight}</b></span>`);
  if (txn.clothType) metaParts.push(`<span>Cloth <b>${txn.clothType} × ${txn.quantity}</b></span>`);
  metaParts.push(`<span>${txn.date} <b>${txn.time}</b></span>`);

  const remainingLabel = txn.remainingBalance !== null ? `₹${rupees(txn.remainingBalance)}` : "—";

  wrap.innerHTML = `
    <span class="timeline-dot"></span>
    <div class="timeline-card txn-card">
      <div class="txn-card-top">
        <span class="txn-token">${txn.id} · ${txn.type}</span>
        <span class="status-chip ${statusClass}">${txn.status}</span>
      </div>
      <p class="timeline-sub">${txn.service}</p>
      <div class="txn-meta">${metaParts.join("")}</div>
      <div class="txn-bottom">
        <span class="txn-amount">₹${rupees(txn.amount)}</span>
        <span class="mini-item-sub">Remaining: ${remainingLabel}</span>
      </div>
    </div>
  `;
  return wrap;
}

/* ---------------------- 16. STAFF VERIFICATION ---------------------- */

document.getElementById("btn-staff-search").addEventListener("click", searchStaffToken);
document.getElementById("staff-token-input").addEventListener("keydown", (e) => {
  if (e.key === "Enter") searchStaffToken();
});

function searchStaffToken() {
  const raw = document.getElementById("staff-token-input").value.trim().toUpperCase();
  const errorEl = document.getElementById("staff-search-error");
  const resultEl = document.getElementById("staff-result");

  if (!raw) {
    errorEl.textContent = "Please enter a token number.";
    resultEl.hidden = true;
    staffActiveTokenId = null;
    return;
  }

  const txn = transactions.find((t) => t.id === raw);

  if (!txn) {
    errorEl.textContent = "Token not found.";
    resultEl.hidden = true;
    staffActiveTokenId = null;
    return;
  }

  if (txn.status !== "Waiting for Verification") {
    errorEl.textContent = `This token has already been ${txn.status.toLowerCase()}.`;
    resultEl.hidden = true;
    staffActiveTokenId = null;
    return;
  }

  errorEl.textContent = "";
  staffActiveTokenId = txn.id;
  populateStaffResult(txn);
  resultEl.hidden = false;
}

function populateStaffResult(txn) {
  document.getElementById("staff-result-token").textContent = txn.id;
  document.getElementById("staff-result-name").textContent = student.name;
  document.getElementById("staff-result-regno").textContent = student.regNo;
  document.getElementById("staff-result-type").textContent = txn.type;
  document.getElementById("staff-result-service").textContent = txn.service;

  const weightRow = document.getElementById("staff-result-weight-row");
  const clothRow = document.getElementById("staff-result-cloth-row");

  if (txn.weight) {
    weightRow.hidden = false;
    document.getElementById("staff-result-weight").textContent = txn.weight;
  } else {
    weightRow.hidden = true;
  }

  if (txn.clothType) {
    clothRow.hidden = false;
    document.getElementById("staff-result-cloth").textContent = `${txn.clothType} × ${txn.quantity}`;
  } else {
    clothRow.hidden = true;
  }

  document.getElementById("staff-result-amount").textContent = `₹${rupees(txn.amount)}`;
  document.getElementById("staff-result-balance").textContent = `₹${rupees(wallet.balance)}`;
  document.getElementById("staff-result-status").textContent = txn.status;
}

document.getElementById("btn-confirm-transaction").addEventListener("click", () => {
  const errorEl = document.getElementById("staff-search-error");
  const txn = transactions.find((t) => t.id === staffActiveTokenId);

  if (!txn) {
    errorEl.textContent = "Token not found. Please search again.";
    document.getElementById("staff-result").hidden = true;
    return;
  }

  if (txn.status !== "Waiting for Verification") {
    errorEl.textContent = `This token has already been ${txn.status.toLowerCase()}.`;
    document.getElementById("staff-result").hidden = true;
    return;
  }

  if (wallet.balance < txn.amount) {
    errorEl.textContent = "Insufficient wallet balance. Transaction cannot be confirmed.";
    return;
  }

  wallet.balance -= txn.amount;
  wallet.totalSpent += txn.amount;
  wallet.count += 1;

  txn.status = "Confirmed";
  txn.remainingBalance = wallet.balance;

  document.getElementById("staff-result").hidden = true;
  document.getElementById("staff-token-input").value = "";
  errorEl.textContent = "";
  staffActiveTokenId = null;

  showToast(`Transaction ${txn.id} confirmed — ₹${rupees(txn.amount)} deducted`);
  renderAll();
});

/* ---------------------- 17. INITIAL RENDER ---------------------- */

function renderAll() {
  renderHome();
  renderCard();
  renderHistory();
}